apiVersion: v1
kind: Namespace
metadata:
  name: ozmos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozmos
  namespace: ozmos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozmos
  template:
    metadata:
      labels:
        app: ozmos
    spec:
      containers:
        - name: nginx
          image: localhost:32000/ozmos:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ozmos
  namespace: ozmos
spec:
  selector:
    app: ozmos
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ozmos
  namespace: ozmos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ozmos.zekisin.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ozmos
                port:
                  number: 80
  tls:
    - hosts:
        - ozmos.zekisin.co
      secretName: ozmos-tls
